### PR TITLE
Issue 53 👷 add a GitHub Action for shellcheck

### PR DESCRIPTION
**Pull request by thomasmerz**
This PR adds a GitHub Action for shellcheck for any push in `master` branch or for every PR - but only when any `*.sh` file has been updated.

### CODE REVIEW

**Comment by thomasmerz** [comment]
I did a "local GH Action run" with [act](https://github.com/nektos/act):
```
🦎🖥  ✔ ~/temp/PRs/fork-mimipenguin [issue_53|✔]
15:20 $ act
[Shellcheck Lint/Shellcheck Lint] 🚀  Start image=ghcr.io/catthehacker/ubuntu:act-latest
[Shellcheck Lint/Shellcheck Lint]   🐳  docker pull image=ghcr.io/catthehacker/ubuntu:act-latest platform= username= forcePull=true
[Shellcheck Lint/Shellcheck Lint]   🐳  docker create image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Shellcheck Lint/Shellcheck Lint]   🐳  docker run image=ghcr.io/catthehacker/ubuntu:act-latest platform= entrypoint=["tail" "-f" "/dev/null"] cmd=[]
[Shellcheck Lint/Shellcheck Lint] ⭐ Run Main actions/checkout@v3
[Shellcheck Lint/Shellcheck Lint]   🐳  docker cp src=/home/thomas/temp/PRs/fork-mimipenguin/. dst=/home/thomas/temp/PRs/fork-mimipenguin
[Shellcheck Lint/Shellcheck Lint]   ✅  Success - Main actions/checkout@v3
[Shellcheck Lint/Shellcheck Lint] ⭐ Run Main Download Shellcheck
[Shellcheck Lint/Shellcheck Lint]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
| shellcheck-stable/LICENSE.txt
| shellcheck-stable/README.txt
| shellcheck-stable/shellcheck
[Shellcheck Lint/Shellcheck Lint]   ✅  Success - Main Download Shellcheck
[Shellcheck Lint/Shellcheck Lint] ⭐ Run Main Check Shellcheck Version
[Shellcheck Lint/Shellcheck Lint]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/2] user= workdir=
| ShellCheck - shell script analysis tool
| version: 0.9.0
| license: GNU General Public License, version 3
| website: https://www.shellcheck.net
[Shellcheck Lint/Shellcheck Lint]   ✅  Success - Main Check Shellcheck Version
[Shellcheck Lint/Shellcheck Lint] ⭐ Run Main Run Shellcheck
[Shellcheck Lint/Shellcheck Lint]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/3] user= workdir=
| shellcheck'ing ./mimipenguin.sh
|
| In ./mimipenguin.sh line 124:
|         export RESULTS="$RESULTS[HIGH]$4            $line\n"
|                         ^-- SC1087 (error): Use braces when expanding arrays, e.g. ${array[idx]} (or ${var}[.. to quiet).
|
|
| In ./mimipenguin.sh line 127:
|             export RESULTS="$RESULTS[LOW]$4         $line\n"
|                             ^-- SC1087 (error): Use braces when expanding arrays, e.g. ${array[idx]} (or ${var}[.. to quiet).
|
| For more information:
|   https://www.shellcheck.net/wiki/SC1087 -- Use braces when expanding arrays,...
| Shellcheck failed for one or more shellscript(s)
[Shellcheck Lint/Shellcheck Lint]   ❌  Failure - Main Run Shellcheck
[Shellcheck Lint/Shellcheck Lint] exitcode '1': failure
[Shellcheck Lint/Shellcheck Lint] 🏁  Job failed
Error: Job 'Shellcheck Lint' failed
🦎🖥  ✔ ~/temp/PRs/fork-mimipenguin [issue_53|✔]
```

**Comment by thomasmerz** [comment]
@huntergregal, has you seen my PR and can review and merge it? Thank you 😗

**Comment by SouthHalfCents** [comment]
您发送的邮件我已经收到，我会尽快查看并回复 。 
//明夕何夕0x00 ***@***.***

**Comment by huntergregal** [comment]
I don't want any github actions.

**Pull request closed without merging**
